"""add visualization field to answers

Revision ID: c99cbf6425b9
Revises: bf7052073f53
Create Date: 2026-03-18 10:27:05.499160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99cbf6425b9'
down_revision = 'bf7052073f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visualization', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('visualization')

    # ### end Alembic commands ###
